# Generated by Django 6.0.6 on 2026-06-15 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Completo', models.TextField(max_length=100)),
                ('Usuario', models.TextField(max_length=25)),
                ('Senha', models.TextField(max_length=12)),
                ('Eh_ADM', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.TextField()),
                ('Prioridade', models.IntegerField(max_length=1)),
                ('Esta_Aberto', models.BooleanField(default=False)),
                ('CategoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('UsuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mensagem', models.TextField()),
                ('ChamadoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chamado')),
            ],
        ),
    ]
