# Generated by Django 6.0.6 on 2026-07-02 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_cpf_alter_chamado_usuarioid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='Comentario',
            field=models.TextField(default='Nada Informado.'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='UsuarioId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
