# Generated by Django 6.0.6 on 2026-07-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chamado_comentario_comentario_usuarioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='Prioridade',
            field=models.IntegerField(),
        ),
    ]
