# Generated by Django 6.0.7 on 2026-07-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chamado_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='Finalizador',
            field=models.TextField(default='John Doe'),
        ),
    ]
